[env:esp32-c3]
platform  = espressif32
board     = esp32-c3-devkitm-1
framework = arduino

monitor_speed = 115200
board_build.partitions = min_spiffs.csv

lib_deps =
    bblanchon/ArduinoJson
    knolleary/PubSubClient

; --- OTA upload (use after first serial flash) ---
; upload_protocol = espota
; upload_port     = hackerspace-status.local
; upload_flags    = --auth=itoldyoualready

[env:esp32-c3-ota]
platform  = espressif32
board     = esp32-c3-devkitm-1
framework = arduino

monitor_speed = 115200
board_build.partitions = min_spiffs.csv

lib_deps =
    bblanchon/ArduinoJson
    knolleary/PubSubClient

; --- OTA upload (use after first serial flash) ---
upload_protocol = espota
upload_port     = 192.168.2.195
;upload_port     = hackerspace-status.local
upload_flags    = --auth=itoldyoualready
